server:
  port: ${SERVER_PORT:8080}

uploadPath: "file:///home/ec2-user/hanspoon_images/"
itemImgLocation: "/home/ec2-user/hanspoon_images"

spring:
  profiles:
    active: dev
  application:
    name: hanspoon

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # [수정] SSL 접속 허용 및 타임존 설정 추가
    url: "jdbc:mariadb://${RDS_HOSTNAME}:3306/hanspoon?serverTimezone=Asia/Seoul&useSSL=true&trustServerCertificate=true"
    username: "${RDS_USERNAME}"
    password: "${RDS_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: update # 데이터가 다 들어온 후에는 none으로 바꾸는 것을 추천합니다.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  web:
    resources:
      static-locations:
        - "classpath:/static/"

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: "${JWT_SECRET}"

kakao:
  rest-api-key: "${KAKAO_REST_API_KEY}"
